export const israelLocationSuggestions = [
  'Tel Aviv',
  'Jerusalem',
  'Haifa',
  'Rishon LeZion',
  'Petah Tikva',
  'Ashdod',
  'Netanya',
  'Beer Sheva',
  'Holon',
  'Bnei Brak',
  'Rehovot',
  'Bat Yam',
  'Herzliya',
  'Kfar Saba',
  'Raanana',
  'Modiin-Maccabim-Reut',
  'Hadera',
  'Ashkelon',
  'Eilat',
  'Tiberias',
  'Nazareth',
  'Afula',
  'Ramat Gan',
  'Givatayim',
  'Ramat Hasharon',
  'Kiryat Ono',
  'Kiryat Gat',
  'Kiryat Yam',
  'Dizengoff St 100, Tel Aviv',
  'Ibn Gabirol St 30, Tel Aviv',
  'Ben Yehuda St 15, Tel Aviv',
  'Rothschild Blvd 50, Tel Aviv',
  'King George St 10, Jerusalem',
  'Jaffa St 120, Jerusalem',
  'Emek Refaim St 25, Jerusalem',
  'Hanevi’im St 35, Jerusalem',
  'Herzl St 75, Haifa',
  'Hanasi Blvd 110, Haifa',
  'Hadar Yosef St 12, Haifa',
  'Herzl St 45, Rishon LeZion',
  'Weizmann St 20, Rehovot',
  'Avi Har-Even St 5, Modiin',
  'Haprozdor St 1, Kfar Saba',
  'Sokolov St 37, Ramat Gan',
  'Bialik St 9, Ramat Gan',
  'Ben Gurion Blvd 1, Bat Yam',
  'Herzl St 100, Netanya',
  'Eilat Rd 2, Beer Sheva',
  'HaAtzmaut Rd 60, Ashdod',
  'HaAliya St 8, Ashkelon',
  'Hagana St 14, Holon',
] as const;
